spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lookAtMe
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /lookAtMe
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
            format_sql: true
    show-sql: true
